### PR TITLE
Generate DEB

### PR DESCRIPTION
**Pull request by TheBrokenRail**

### CODE REVIEW

**Comment by TheBrokenRail** [comment]
@MCMrARM

**Comment by TheBrokenRail** [comment]
Any updates?

**Comment by MCMrARM** [comment]
Would you mind updating this to the more recent CPackOptions.txt format?

**Comment by TheBrokenRail** [comment]
Done!

**Comment by TheBrokenRail** [comment]
@MCMrARM

**Comment by TheBrokenRail** [comment]
@MCMrARM Any Updates?

**Comment by TheBrokenRail** [comment]
Any update, its been a month.

**Comment by TheBrokenRail** [comment]
@MCMrARM is there any more changes that should be made to this?

**Comment by MCMrARM** [comment]
Please remove the `libpng, libevdev, libudev` dependencies, and then please test it on at least one of the supported systems.

**Comment by TheBrokenRail** [comment]
@MCMrARM Removed redundant dependencies, and successfully generated DEB file.

[mcpelauncher-server-d9cc8d9-Linux.zip](https://github.com/minecraft-linux/mcpelauncher-server/files/3483260/mcpelauncher-server-d9cc8d9-Linux.zip)

**Pull request merged**
